name: pongs
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  firebase_auth: ^4.6.3
  firebase_storage: ^11.2.4
  firebase_core: ^2.4.0
  firebase_database: ^10.0.8
  flutter_bloc: ^8.1.3
  get_it: ^7.1.6
  google_fonts: ^4.0.3
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  uuid: ^4.2.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/logo/
    - assets/img/game_icons/
    - assets/img/search_magnify/

 
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
          weight: 400

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
    
    - family: IconsPongs
      fonts:
        - asset: assets/icons/IconsPongs.ttf
 