/// Flutter icons MyFlutterApp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconsPongs
///      fonts:
///       - asset: fonts/IconsPongs.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconsPongs {
  IconsPongs._();

  static const _kFontFam = 'IconsPongs';
  static const String? _kFontPkg = null;

  static const IconData account_circle = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_image = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_flip = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_circle = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData choop = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData decrement = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gamepad = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_outline = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_variant = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData increment = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData log_off = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData users_multiple = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
